// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinallShope.Migrations
{
    [DbContext(typeof(FinallShopeContext))]
    partial class FinallShopeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinallShope.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopeId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.DescraptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("DescraptionItem");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatogryId")
                        .HasColumnType("int");

                    b.Property<string>("Descraption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemPhtoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatogryId");

                    b.HasIndex("ItemPhtoId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.ItemPhto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemPhto");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Shope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shope");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Category", b =>
                {
                    b.HasOne("FinallShope.DAL.Entities.Shope", "Shope")
                        .WithMany("Categories")
                        .HasForeignKey("ShopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shope");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.DescraptionItem", b =>
                {
                    b.HasOne("FinallShope.DAL.Entities.Item", "Item")
                        .WithMany("DescraptionItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Item", b =>
                {
                    b.HasOne("FinallShope.DAL.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CatogryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinallShope.DAL.Entities.ItemPhto", "ItemPhto")
                        .WithMany("Items")
                        .HasForeignKey("ItemPhtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ItemPhto");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Item", b =>
                {
                    b.Navigation("DescraptionItems");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.ItemPhto", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FinallShope.DAL.Entities.Shope", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
